backend:
  name: git-gateway
  repo: anhmht/headless-cms
  branch: master
local_backend: true # run npx netlify-cms-proxy-server for local testing
publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/post/vn'
    create: true
    slug: '{{slug}}'
    sort: 'date:desc'
    fields:
      - { label: 'ID', name: 'id', widget: 'uuid' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'category',
          value_field: 'id',
          search_fields: ['title', 'id'],
          display_fields: ['title'],
          required: true
        }
      - {
          label: 'Is Banner',
          name: 'isBanner',
          widget: 'boolean',
          default: false
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: Summary 10-220,
          name: summary,
          widget: text,
          required: true,
          pattern: ['.{10,200}', 'Must be within 10 and 220 characters']
        }
      - { label: 'Publish Date', name: 'date', widget: 'date', required: true }
      - {
          label: 'Updated Date',
          name: 'update',
          widget: 'date',
          required: false
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'postEN'
    label: 'postEN'
    folder: 'content/post/en'
    create: true
    slug: '{{fields.postVN}}'
    sort: 'date:desc'
    identifier_field: postVN
    fields:
      - { label: 'ID', name: 'id', widget: 'uuid' }
      - {
          label: 'PostVN',
          name: 'postVN',
          widget: 'relation',
          collection: 'post',
          value_field: 'title',
          search_fields: ['title', 'id'],
          display_fields: ['title'],
          required: true
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: Summary 10-220,
          name: summary,
          widget: text,
          required: true,
          pattern: ['.{10,200}', 'Must be within 10 and 220 characters']
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'category'
    label: 'Category'
    folder: 'content/category'
    create: true
    slug: '{{slug}}'
    sort: 'date:desc'
    fields:
      - { label: 'ID', name: 'id', widget: 'uuid' }
      - { label: 'Title-EN', name: 'titleEN', widget: 'string', required: true }
      - { label: 'Title-VI', name: 'title', widget: 'string', required: true }
